DROP TABLE IF EXISTS email_to;
DROP TABLE IF EXISTS email_cc;
DROP TABLE IF EXISTS emails;

-- Crear la tabla  `emails`
CREATE TABLE emails (
                        email_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- ID del correo
                        email_from VARCHAR(255) NOT NULL,                              -- Correo del remitente
                        email_body TEXT NOT NULL,                                      -- Cuerpo del correo
                        state INT CHECK (state IN (1, 2, 3, 4)),       -- Cuatro estados válidos
                        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP                 -- Fecha de actualización
);

-- Crear la tabla `email_to`
CREATE TABLE email_to (
                          to_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,    -- ID único para cada destinatario "To"
                          email_id BIGINT REFERENCES emails(email_id) ON DELETE CASCADE, -- Relación con la tabla emails
                          email VARCHAR(255) NOT NULL                                   -- Dirección de email del destinatario "To"
);

-- Crear la tabla `email_cc`
CREATE TABLE email_cc (
                          cc_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,    -- ID único para cada destinatario "CC"
                          email_id BIGINT REFERENCES emails(email_id) ON DELETE CASCADE, -- Relación con la tabla emails
                          email VARCHAR(255) NOT NULL                                   -- Dirección de email del destinatario "CC"
);
